
systemLog:
  destination: file
  path: C:\Program Files\MongoDB\Server\4.2\log\mongod.log
  logAppend: true
storage:
  dbPath: C:\Program Files\MongoDB\Server\4.2\data

net:
  bindIp: 0.0.0.0

 # mongod --config "C:\Program Files\MongoDB\Server\4.2\bin\mongo.conf" --install --serviceName "MongoDB"
 #mongod --config "C:\Program Files\MongoDB\Server\4.2\bin\mongo.conf"
